# Generated by Django 4.2.13 on 2024-08-20 10:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('picture', models.ImageField(upload_to='myapp/static/task_pictures/')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('wallet', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('level', models.IntegerField(default=1)),
                ('energy', models.IntegerField(default=1000)),
                ('energy_limit', models.IntegerField(default=1000)),
                ('multitap_level', models.IntegerField(default=1)),
                ('tap_efficiency', models.IntegerField(default=1)),
                ('energy_limit_level', models.IntegerField(default=1)),
                ('last_energy_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('invited_by', models.TextField(blank=True, null=True)),
                ('users_invited', models.TextField(blank=True, default='', null=True)),
                ('highest_invited_wallets_sum', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('last_daily_bonus', models.DateTimeField(blank=True, null=True)),
                ('daily_energy_last_daily_bonus', models.DateTimeField(blank=True, null=True)),
                ('daily_turbo_last_daily_bonus', models.DateTimeField(blank=True, null=True)),
                ('last_mining_bonus', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Start'), (2, 'Claim'), (3, 'Done')], default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
    ]
