# Generated by Django 4.2.13 on 2024-08-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task_timer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recieved_threefriends_reward',
            field=models.BooleanField(default=False),
        ),
    ]
