# Generated by Django 4.2.13 on 2024-07-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_coins_per_tap_userprofile_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='multitap_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tap_efficiency',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
    ]
