# Generated by Django 5.1 on 2024-08-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task_timer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_rewards',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
