# Generated by Django 5.1 on 2024-09-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile_telegram_rewards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='energy_limit',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='energy_limit_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='multitap_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tap_efficiency',
        ),
    ]
