# Generated by Django 5.0.3 on 2024-08-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile_recieved_threefriends_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_daily_bonus',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
