# Generated by Django 4.2.13 on 2024-07-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile_multitap_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20000000),
        ),
    ]
