# Generated by Django 4.2.13 on 2024-08-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile_recieved_threefriends_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_12h_task',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
