# Generated by Django 4.2.13 on 2024-08-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile_last_12h_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_daily_bonus',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
