# Generated by Django 5.1 on 2024-09-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_telegram_sub_tasks_alter_userprofile_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegram_sub_tasks',
            old_name='channel_id',
            new_name='chat_id',
        ),
        migrations.RenameField(
            model_name='telegram_sub_tasks',
            old_name='link',
            new_name='url',
        ),
    ]
