# Generated by Django 4.2.13 on 2024-07-07 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_userprofile_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_energy_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
    ]
