# Generated by Django 5.1 on 2024-09-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_channel_id_telegram_sub_tasks_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_sub_tasks',
            name='chat_id',
            field=models.CharField(max_length=50),
        ),
    ]
