# Generated by Django 5.1 on 2024-09-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_telegram_sub_tasks_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_firstname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
