# Generated by Django 5.1 on 2024-10-01 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_last_12h_task_userprofile_last_12h_task_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
