# Generated by Django 4.2.13 on 2024-07-12 20:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_userprofile_referrer_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='used',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inviter',
            field=models.ManyToManyField(related_name='invited', to='myapp.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_token',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_referrals', to='myapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
