# Generated by Django 5.1.1 on 2024-10-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_userprofile_joined_userprofile_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='taskyt_status',
            field=models.BooleanField(default=True),
        ),
    ]
