# Generated by Django 4.2.13 on 2024-07-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.IntegerField(choices=[(1, 'Claim'), (2, 'Start'), (3, 'Done')], default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.task')),
            ],
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='referral_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='referrer',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invited_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='users_invited',
            field=models.TextField(default=''),
        ),
    ]
