# Generated by Django 4.2.13 on 2024-07-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_referral_invited_alter_referral_referrer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='highest_invited_wallets_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
