# Generated by Django 4.2.13 on 2024-07-16 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_userprofile_highest_invited_wallets_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskuser',
            name='name',
        ),
        migrations.AddField(
            model_name='taskuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile'),
            preserve_default=False,
        ),
    ]
