# Generated by Django 4.2.13 on 2024-07-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_taskuser_name_taskuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='users_invited',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
