# Generated by Django 4.2.13 on 2024-07-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_userprofile_users_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_daily_bonus',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
