# Generated by Django 4.2.13 on 2024-07-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_userprofile_last_daily_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Start'), (2, 'Claim'), (3, 'Done')], default=1),
        ),
    ]
