# Generated by Django 4.2.13 on 2024-07-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_task_link_alter_taskuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='users_invited',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
