# Generated by Django 4.2.13 on 2024-07-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_task_name_alter_userprofile_users_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='turbo_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='turbo_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
