# Generated by Django 4.2.13 on 2024-07-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_userprofile_turbo_activated_userprofile_turbo_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='coins_per_tap',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='turbo_activated',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='turbo_expiry',
        ),
    ]
