# Generated by Django 4.2.13 on 2024-07-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_userprofile_coins_per_tap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='energy_limit',
            field=models.IntegerField(default=1000),
        ),
    ]
