# Generated by Django 4.2.13 on 2024-07-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_userprofile_daily_energy_last_daily_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_turbo_last_daily_bonus',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
