# Generated by Django 4.2.13 on 2024-07-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_userprofile_daily_turbo_last_daily_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='picture',
            field=models.ImageField(default=2, upload_to='task_pictures/'),
            preserve_default=False,
        ),
    ]
