# Generated by Django 4.2.13 on 2024-07-25 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_task_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('mining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mining')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
    ]
