# Generated by Django 4.2.13 on 2024-07-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_miningcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mining',
            name='picture',
            field=models.ImageField(upload_to='mining_pictures/myapp/static'),
        ),
    ]
