# Generated by Django 4.2.13 on 2024-07-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_mining_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mining',
            name='picture',
            field=models.ImageField(upload_to='myapp/static/mining_pictures'),
        ),
    ]
