# Generated by Django 4.2.13 on 2024-07-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_task_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_mining_bonus',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
