# Generated by Django 4.2.13 on 2024-07-30 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_category_mining_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mining',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
