# Generated by Django 4.2.13 on 2024-08-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_mining_cost_10_mining_cost_11_mining_cost_12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_10',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_11',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_12',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_13',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_14',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_15',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_16',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_17',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_18',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_19',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_20',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mining',
            name='income_per_hour_9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_10',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_11',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_12',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_13',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_14',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_15',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_16',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_17',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_18',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_19',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_2',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_20',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_3',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_4',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_5',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_6',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_7',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_8',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='cost_9',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='mining',
            name='income_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
