# Generated by Django 4.2.13 on 2024-08-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_mining_income_per_hour_10_mining_income_per_hour_11_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mining',
            old_name='name',
            new_name='name_eng',
        ),
        migrations.AddField(
            model_name='mining',
            name='name_rus',
            field=models.CharField(default='r', max_length=50),
            preserve_default=False,
        ),
    ]
