# Generated by Django 4.2.13 on 2024-08-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_rename_name_mining_name_eng_mining_name_rus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mining',
            old_name='about',
            new_name='about_eng',
        ),
        migrations.AddField(
            model_name='mining',
            name='about_rus',
            field=models.TextField(default='about rus', max_length=50),
            preserve_default=False,
        ),
    ]
